services:
  postgres:
    image: postgres:15-alpine
    container_name: social-network-db
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./volumes/social-network-db:/var/lib/postgresql/data
    networks:
      - social-network_pgnet

  pgslave:
    image: postgres:15-alpine
    container_name: pgslave
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - pgslave_data:/var/lib/postgresql/data
      - ./volumes/pgslave:/var/lib/postgresql/data
    networks:
      - social-network_pgnet

  pgasyncslave:
    image: postgres:15-alpine
    container_name: pgasyncslave
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
    volumes:
      - pgasyncslave_data:/var/lib/postgresql/data
      - ./volumes/pgasyncslave:/var/lib/postgresql/data
    networks:
      - social-network_pgnet

  redis:
    image: redis:7-alpine
    container_name: social-network-redis
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - social-network_pgnet

  app:
    build: .
    container_name: social-network-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - social-network_pgnet

volumes:
  postgres_data:
    driver: local
  pgslave_data:
    driver: local
  pgasyncslave_data:
    driver: local
  redis_data:
    driver: local
  go-mod-cache:
    driver: local

networks:
  social-network_pgnet:
    driver: bridge